### PR TITLE
Make it possible to configure failover mqtt servers

### PR DESCRIPTION
**Pull request by Spindel**
This adds a "servers" setting, removing the "server" one, making it possible to configure fail-over MQTT servers for use with HA MQTT configurations.

To avoid confusion around what happens when "server" is set and "servers" is not, vs. what happens when server is not part of servers, this removes the old "server" setting and forces it to be a single array of servers, similar to how Redis configuration is done.

This means that upgrading may require a configuration change.

### CODE REVIEW

**Comment by brocaar** [comment]
Before we decide if this should be merged, could you explain a bit better in which cases this should be used or required?

For example, this is how VerneMQ describes a typical deployment:
image

https://docs.vernemq.com/guides/typical-vernemq-deployment

In this case there wouldn't be a need for `servers`, as the LB will be the single endpoint, forwarding connections to one of the available cluster nodes. In case one would be deploying ChirpStack using Kubernetes, then you would simply use the service name of the MQTT broker, and Kubernetes will handle the loadbalancing.

In the past, providing the `servers` option in the ChirpStack Gateway Bridge has been a source of confusion. Users expected that the data would be forwarded to multiple servers simultaneously rather than the first server available.

**Comment by Spindel** [comment]
Apologies for that confusion, Here the goal is to reduce the LB as a single point of failure and let the clients automatically fail-over between the endpoints.  This is more important when distributing things geographically, and against network partitions (which of course requires some other concerns when it comes to ensuring robustness).

So, this is a complementary part compared to LB setup, where the clients can manage it. It hsould be noted that the same support is built into postgresql and other data backends already as part of the connection strings.

To avoid the configuration file confusion, I could keep the "server" setting and then also expose "extra_servers" as an array of extras, but I wanted to reduce the amount of maybe confusing options of server/Servers/etc.   (Another alternative is ofc. to string-split on a magic character, like comma,  in the server line, but that strikes me as even worse.)

**Comment by brocaar** [comment]
Thanks for your response. However, I'm still not sure if we should add this. It adds more flexibility, but it has caused confusion in the past. As well, not having this option does not prevent one to setup MQTT in HA. Some options that are already possible I believe are:

* Load-balancer (single endpoint, multiple backends)
* DNS (multiple A records for round-robin balancing)
* Use Kubernetes for service discovery (local DNS that resolves to healthy MQTT node)
* Use Consul for service discovery (local DNS that resolves to healthy MQTT node, see also https://www.consul.io/use-cases/discover-services)

The advantages that I see when using one of the above options is that in case one MQTT instance would fail, ChirpStack is able to recover without any configuration change at the ChirpStack side. Therefore, adding / removing MQTT nodes does not affect the ChirpStack configuration.

**Comment by brocaar** [comment]
I'm closing this issue. With the migration from paho to rumqttc (to reduce the amount of c dependencies), I'm not sure if this is still a possibility: https://docs.rs/rumqttc/latest/rumqttc/v5/struct.MqttOptions.html#impl-MqttOptions.

**Pull request closed without merging**
