### PR TITLE
Add type stubs to python API bindings

### PR DESCRIPTION
**Pull request by ldorigo**
Similar to https://github.com/brocaar/chirpstack-api/pull/62 for chirpstack 4.

### CODE REVIEW

**Comment by ldorigo** [comment]
Hi, yes, you are right - I included that python package in the requirements in the makefile for the other pull request I made (https://github.com/brocaar/chirpstack-api/pull/62/files#diff-be6956a404d1f0e80d893f44543318c575770a7c09d511e95c8087c2bdafef88 ) but forgot to add it here. I am not sure if your version also generates .pyi files for grpc ? I will try to test it at some point but it could be a while.

**Comment by brocaar** [comment]
> I am not sure if your version also generates .pyi files for grpc ? I will try to test it at some point but it could be a while.

I'm not sure, but if we can avoid using additional libraries, then I prefer to go with the "official" protobuf option.

**Comment by brocaar** [comment]
@ldorigo the above commit adds the `--pyi_out` flag to generate Python type information.

**Comment by ldorigo** [comment]
Hi @brocaar - it's up to you whether you care or not, but the commit with which you closed this does not produce type information for grpc files, which the original PR did. Not sure whether the addition of a compile-time dependency is such  big deal? It doesn't change anything for end-users.

**Pull request closed without merging**
