### PR TITLE
Resync channels if chmask NACK'ed in LinkADRAns

### PR DESCRIPTION
**Pull request by sp193**
Handle a chmask not being acknowledged in LinkADRAns, which is an indicator that the device's knowledge of channels differs from Chirpstack's. This may happen if the device (silently) rejected channel(s) during OTAA, but there is no mechanism for the device to convey this.

I do not have that device now, but I think it should work.
It went along the lines of:
1. Device joins the network via OTAA. LNS configures some channels via OTAA.
2. Device rejects some of the channels, but the LoRaWAN specification provides no way for the device to convey this action to the LNS.
3. ADR fails because LNS thinks that all the channels are configured, but some are not. The device will NACK chmask.

In my LNS, my solution was to clear the configured channels list upon encountering the chmask getting NACK'ed, before re-configuring the channels with NewChannelReq. So that the unsupported channels can be identified and dropped.

The device I encountered was a Sensoneo Single Sensor 3.0, with firmware 188. In AS923, the specification has an ambiguity regarding the datarates: DR0 and DR1 are assumed to be unsupported by default, but the CFList part of the JOIN ACCEPT is for DR0-5. So this device rejected any request for channels with DR0. I think it's a weird or even wrong design, but such a thing exists and will cause the device to always operate at the lowest datarate.

Anyway, I think you may encounter this error with other devices, if the device cannot support the specified frequency.

### CODE REVIEW

**Comment by sp193** [comment]
I realize that my RisingHF RF3M076 meets this test criteria, whereby the 922.0MHz channel (which is an extra channel) is rejected during OTAA due to its frequency, making its knowledge of channels inconsistent with that of Chirpstack's. With this patch, Chirpstack will be able to work with the ADR implementation of such a device.

**Comment by brocaar** [comment]
Note that an out-of-sync channel-plan is one of the reasons for nacking the channel-mask, it is not always the case:

image

If one of the other cases is true, then it would incorrectly clear out the custom channels.

> In AS923, the specification has an ambiguity regarding the datarates: DR0 and DR1 are assumed to be unsupported by default,

Could you let me know where this is stated in the specification? I have found:

image

I think this is quite clear, it refers to the data-rate used for the JoinRequest message. It does not apply to the CFList frequencies, as these will be used for (Un)confirmedDataUp.

---

According the LoRaWAN specs:

image

There is no mentioning of silently dropping channels. By merging this pull-request, we might solve one problem, but create an other.

**Comment by sp193** [comment]
Hi.

Regarding the other meaning of the LinkADRAns ChannelMaskACK bit: in that case (whereby the TxPower and/or DR cannot be supported with the CH mask), LinkADRReq should still eventually become disabled after the 2nd attempt. This is Chirpstack's present behaviour.
If you thought that we should have logic to handle this case (which I honestly didn't realize was an addition to the new spec version), then I think another (separate) PR should be made to handle that situation?

---

Regarding the ambiguity regarding whether DR0 and DR1 should be supported in AS923: I have nothing to quote, but that is just the issue: the definition for JOIN ACCEPT shows DR0-5 as the semantics for the channels set in that way. I just happened to have one device that worked in this fashion, much to my annoyance. I personally think it is an unusual way to interpret that able and the blame would lie more on the shoulders on the folks who interpreted the table in such a way.

However, this situation can also occur if the device cannot work with the channels specified within the CFList, such as incompatibilities with the centre frequencies. As with what I've been trying to sell in my other PR, I think it would be good if Chirpstack would have an amicable way to handle such a device, without just getting dead-ended.

After all, if the device can reject channels via NewChannelReq/NewChannelAns because of hardware limitations preventing compatibility with the given frequency and/or datarates, surely the same channels cannot be accepted via JOIN ACCEPT?

**Comment by brocaar** [comment]
> All these channels are usable for DR0 to DR5 125 KHz LoRa modulation.

Which is in my opinion correct.

* Device sends OTAA JoinRequest using DR2-DR5 (DR2-DR5 limitation is for JoinRequest only!)
* ChirpStack responds with JoinAccept + CFList
* Device can use CFList channels using DR0 - DR5 for (Un)confirmed uplinks

See also:

image
can reject channels via NewChannelReq/NewChannelAns because of hardware limitations preventing compatibility with the given frequency and/or datarates, surely the same channels cannot be accepted via JOIN ACCEPT?

> After all, if the device can reject channels via NewChannelReq/NewChannelAns because of hardware limitations preventing compatibility with the given frequency and/or datarates, surely the same channels cannot be accepted via JOIN ACCEPT?

Some devices might not support all data-rates, e.g. they might not support the LR-FHSS modulation, but these data-rates are not included in the CFList and can only be configured using the NewChannelReq mac-command.

I don't think a scenario where some devices support the CFList channels and some don't is valid. Of course you could send frequencies which are out of range, but then it would cause issues for all devices.

**Comment by sp193** [comment]
Hi again,

I agree with what you wrote too. But that is the thing - there can be devices that don't really work as we would hope they should.

---

But what about cases where the device does not accept channels because of incompatibility with the centre frequencies? As mentioned in my latest post in #346, the specification permits devices to reject channels configured with NewChannelReq. If they reject channels because they physically cannot support the centre frequencies, I do not suppose it makes sense for them to support them via OTAA?

I am not referring to very unusual frequencies or datarates. My region (AS923-1) is defined as being loosely 920-925MHz. The exact range depends on your local regulations, like my laws now permit 917-925MHz, while my neighbouring countries have different ISM band allocations.

But I have a node which rejects 922.0MHz for some reason, while other nodes do not have an issue with this specific channel. I didn't try lower channels like 921.8MHz, so it could be possible that the device doesn't work with anything below 922.2MHz.

**Comment by sp193** [comment]
Regarding the change of the description of the ChannelMaskAck bit in LinkADRAns at LoRaWAN 1.0.4: I think the change is supposed to clarify some behaviour that the LoRa Alliance wished to cater for, but I might not know how all the conditions for the channel mask to become incompatible with the datarate and transmission power. And how this situation differs from the device NACK'ing DataRateACK and/or PowerACK.

Personally, I believe it refers to a situation where _no channels_ can be used if the channel mask is accepted, due to the remaining channels being incompatible with the given datarate and/or Tx power (e.g. out of range for the local regulations). For example, if you are using something DR6 and you disable the LoRa STD channel. But this is not a datarate that will be used at the beginning.

So how about we only re-sync the channels, only during the first attempt at ADR? I think this would be good enough, since the problem only occurs immediately after OTAA. I don't know about the rejoin procedure of LoRaWAN 1.1, as my LNS only supports up to 1.0.3.
I think we can choose to bind this to either the error counter for LinkADRReq or to add a new attribute in the DeviceSession to track whether we have started sending LinkADRReq before within the session.

**Comment by sp193** [comment]
Hi @brocaar I don't mean to push if you're busy, still thinking about it or just want to continue this discussion at some other time.

I'm just very keen to see Chirpstack have better handling of this area (and the others that I've been trying to bring up). I want to try to explaining my views better as I have been physically tired due to work-related issues (which probably impairs my thinking).
I thought that I didn't do so well above, so please allow me to try elaborating further.

---

I shouldn't have used the Sensoneo device as an example, as it's clearly more of a firmware design issue. This change helped that device by identifying that it rejected all additional channels. But that is not the point of this change.

The focus of this PR and #346 should have been on the fact that there can be hardware limitations by nodes, whereby the node may not be able to/not allowed to use all frequencies (as described by 5.6 Creation/Modification of a Channel). The NewChannelAns MAC command response allows the device to reject unsupported frequencies:
> The end-device SHALL check that the frequency is allowed by its radio hardware and SHALL NOT set the channel frequency bit ... if the end-device cannot use this frequency (see below).

In section 6.2.6 Join-Accept frame, the following is mentioned with regards to the CFList:
> The end-device behaviour when processing CFList SHALL be identical to what would result from processing those MAC commands if they were received in a single downlink frame...with the exception that CFList processing does not generate a MAC answer.

So if channels can be rejected via NewChannelReq, this clause implies that the channels listed within the Join Accept's CFList can be rejected without a response.

---

You mentioned that you don't think that a scenario where some devices support the CFList channels and some don't is valid. And also that the frequency range that devices must support are defined in the regional parameters, [in this comment](https://github.com/chirpstack/chirpstack/pull/346#issuecomment-1881382507).
I think that both points make sense for regions like EU868 and US915, which have well-defined ranges. Such regions are backed by clear standards. If I am not mistaken, FCC's rules defined US915, while ESTI's rules defined EU868.

But AS923 covers large parts of Asia (and perhaps even more), which has many countries with different regulations. And our possible ISM band ranges and rules are varied. Devices may have RF filters to help with coexistence with other RF technologies. To think about it, I know that my Kerlink Wirnet Station 923 gateways have additional filters (compared to the Kerlink Wirnet Station 915) to help with coexistence with our local cellular towers. What I understood about this topic, is that the demodulator can become desensitized without the right filters, as the other RF modulations would appear as noise. However, the filters also limit the supported frequency range. Something similar should exist for nodes as well.

LoRaWAN 1.0.3's regional parameters document defined AS923 as just:
> where the frequencies [923...923.5MHz] are comprised in the ISM band.

Which implies that any region including this range can be considered as part of AS923. The description was vastly changed with 1.0.4, but it still doesn't cover a specific range of frequencies.

I think it makes sense if we find devices that could work between the various 900MHz regions, which might not be entirely perfectly compatible across all of them. Perhaps programming them to reject channels (rather than underperforming) is a strong-armed move, but it is allowed by the specification's definition of NewChannelReq/NewChannelAns.

---

Thank you for taking the time to read and understand this message, and perhaps also the time taken to respond to it.

**Comment by brocaar** [comment]
Thanks for your work on this topic, but I will close this issue as well. I know you have been trying to solve various issues, but these are all the result of malfunctioning devices or devices that selectively implement the LoRaWAN specification. These kind of work-around solutions have a cost that I prefer to not maintain. These add additional complexity to the code-base, but also can have side-effects for devices that do behave properly as I have tried to outline in my comments.

> This may happen if the device (silently) rejected channel(s) during OTAA, but there is no mechanism for the device to convey this.

You are right that for the CFList channels that there isn't a mechanism to communicate incompatible frequencies, but I think it would be better to clarify this with the LoRa Alliance. Please note that the Regional Parameters specification defines the frequency-range that the device must implement. If this is missing for a region, then I think it would be good to provide this info to the LoRa Alliance such that the specification can be improved.

 For AS923 these are defined here:

image

You will find the exact min / max frequencies in the LoRaMacNode implementation for these regions:

https://github.com/Lora-net/LoRaMac-node/blob/master/src/mac/region/RegionAS923.c#L60

**Pull request closed without merging**
