### PR TITLE
fix as923 maxpayload table due to change in R002-1.0.0 regional param…

### PR DESCRIPTION
**Pull request by kelah**
…eters specs.

### CODE REVIEW

**Comment by brocaar** [comment]
I noticed an other mistake in AS923. In RP002-1.0.0 in one of the tables 250 was changed to 230.

**Comment by brocaar** [comment]
I have fixed this in the above commit. Could you do a second validation on the updated values?

**Comment by kelah** [comment]
The changes of maxpayload 250 -> 230 is only for "repeater + dwell time" configuration. "no repeater + dwell time" config should not change. I think the original code is correct.

    On Friday, September 29, 2023 at 06:19:54 PM GMT+8, Orne Brocaar ***@***.***> wrote:  
 
 


I have fixed this in the above commit. Could you do a second validation on the updated values?

**Comment by brocaar** [comment]
Yes, you are right. I have pushed one more fix.

**Comment by kelah** [comment]
Noted.Sent from my iPhoneOn Oct 2, 2023, at 9:01 PM, Orne Brocaar ***@***.***> wrote:﻿
Yes, you are right. I have pushed one more fix.

**Pull request closed without merging**
