### PR TITLE
Protobuf API: add C support

### PR DESCRIPTION
**Pull request by valcarcexyz**
This pull request adds support for the C language to use the protobuf API.  It is useful for gateways written in C build with chirpstack in mind to be able to skip the UDP packet forwarder, as it uses way more bytes to send the same data at the end.

It follows the structure of the others implementations, with some caveats:

- There is no official support for the C language for protobuf, so this uses this implementation: https://github.com/protobuf-c/protobuf-c
- There is a sed replace in c/Makefile to rename the `stdin`, `stdout` and `stderr` variables, that would be conflictive with C data types.

### CODE REVIEW

**Comment by brocaar** [comment]
Thanks! :+1: 

> This pull request adds support for the C language to use the protobuf API. It is useful for gateways written in C build with chirpstack in mind to be able to skip the UDP packet forwarder, as it uses way more bytes to send the same data at the end.

I'm not sure if I fully understand your use-case. Isn't this what the ChirpStack MQTT Forwarder is providing?

**Comment by valcarcexyz** [comment]
> I'm not sure if I fully understand your use-case. Isn't this what the ChirpStack MQTT Forwarder is providing?

Yes, and no. The MQTT forwarder acts as a middleware between the gateway and chirpstack. If the gateway will only run with chirpstack, we can just remove the UDP packet forwarder from the Gateway and send the packets received from the concentrator directly to the MQTT broker, which reduces the overall computation needed in the gateway, reducing thus current consumption.

**Comment by brocaar** [comment]
Understood, thanks for the clarification :+1:

**Comment by giobauermeister** [comment]
I think that fits my use case. I have a gateway running a C application alongside Chirpstack application. Right now I'm using shell scripts that call grpcurl application that in turn communicates with Chirpstack gRPC API. I use that for example to add the gateway mac address in which chirpstack is running.

If I understood correctly, with this C support, I could add the gateway mac address directly from my C application, or even add LoRa end devices to chirpstack, without relaying on shell scripts and grpcurl.

**Pull request merged**
